# Generated by Django 4.2.6 on 2023-10-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vrf',
            old_name='Netowrk_Address',
            new_name='Network_Address',
        ),
        migrations.RenameField(
            model_name='vrf',
            old_name='Netowrk_Mask',
            new_name='Network_Mask',
        ),
    ]
