# Generated by Django 4.2.6 on 2023-10-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_app', '0002_rename_netowrk_address_vrf_network_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='eBGP_Peer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Remote_Peer_IP', models.CharField(max_length=1000)),
                ('Remote_As', models.CharField(max_length=1000)),
                ('BGP_Description', models.CharField(max_length=1000)),
                ('In_Prefix_Name', models.CharField(max_length=1000)),
                ('Out_Prefix_Name', models.CharField(max_length=1000)),
                ('Client_Public_IP', models.CharField(max_length=1000)),
                ('Mask_Length', models.CharField(max_length=1000)),
            ],
        ),
    ]
